name: LogCabinScotland
favicon: null
layout_spectrum: 0.30614170455373824
typography_spectrum: 0.22153577348217368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.050052385311573744
  lightness: 0.6040141854900867
  saturation: 0.9773357899393886
  rhythmicContrast: 0.8361593948211521
purpose: []
